project:
  type: website
  output-dir: _site
  preview:
    port: 4200

website:
  title: "NIEHS Scientific Developers Guide"
  back-to-top-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - sidebar:ai

  sidebar:
    - id: ai
      title: "{{< iconify arcticons access >}} AI"
      style: "docked" # All other sidebars inherit this style
      background: light # All other sidebars inherit this style
      collapse-level: 2
      contents: 
        - auto: "ai/*.qmd"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

