project:
  type: website
  output-dir: _site
  preview:
    port: 4200

website:
  title: "NIEHS Scientific Developers Guide"
  back-to-top-navigation: true
  navbar:
    left:
      - href: ai/index.qmd
        text: "{{< iconify hugeicons artificial-intelligence-04 >}} AI"
      - href: analysis/index.qmd
      - href: computing/index.qmd
      - href: data/index.qmd
      - href: deployment/index.qmd
      - href: development/index.qmd
      - href: devops/index.qmd
      - href: resources/index.qmd
      - href: software/index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

