project:
  type: website
  output-dir: _site
  preview:
    port: 4200

website:
  title: "NIEHS Scientific Developers Guide"
  back-to-top-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: ai/index.qmd
        text: AI
      - href: computing/index.qmd
        text: Computing
      - href: data/index.qmd
        text: Data
      - href: deployment/index.qmd
        text: Deployment
      - href: devops/index.qmd
        text: DevOps
      - href: resources/index.qmd
        text: Resources
      - href: software/index.qmd
        text: Software

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

