---
title: "NIEHS Scientific Developers Guide"
date-modified: "2024-06-19"
---

## Welcome 

Welcome to the NIEHS Scientific Developers Guide. This guide is intended to provide a set of best practices and guidelines for developing scientific software at NIEHS. The guide is intended to be a living document and will be updated as new best practices emerge.

## What is a "Scientific Developer"?

What constitutes a **"scientific developer"**? These are people who typically:

- use R or Python (or Julia, MATLAB, SAS, etc...) to process scientific data
- utilize scientific notebooks and publishing tools such as Jupyter, RMarkdown, Quarto, LaTeX, etc., to analyze data and create publications
- use high-performance computing (HPC) to enable large analytical pipelines
- store and interact with large amounts of data, including GB or TB (or even larger!) datasets
- create plots of all kinds and share their results in interactive ways (hello Shiny!)

This page is meant to support these developers, as well as the people who work closely with them (shoutout to the [Office of Scientific Computing](https://www.niehs.nih.gov/research/atniehs/dir/sio) and the [Office of Data Science](https://www.niehs.nih.gov/about/od/osec/osim)).

