---
title: "Communities"
date: "2024-07-27"
---

## Introduction

Welcome to the NIEHS Communities Guide. This guide is intended to direct you to the various NIEHS communities that you can join to connect with other researchers, share knowledge, and collaborate on projects.

## ListServs

- **[AI@LIST.NIH.GOV](https://list.nih.gov/cgi-bin/wa.exe?A0=AI)**: This listserv is for researchers interested in artificial intelligence and machine learning, run by the NIH AI Interest Group.
- **[AI-CLUB@LIST.NIH.GOV](https://list.nih.gov/cgi-bin/wa.exe?A0=AI-CLUB)**: Official list for AI Club. Subscribe for calendar invites to our AI Club journal clubs, workshops, and seminars, as well as other AI-related events and news on NIH Bethesda campus.
- **[APSIG@LIST.NIH.GOV](https://list.nih.gov/cgi-bin/wa.exe?A0=APSIG)**: The purpose of the NIH Artificial Intelligence (AI) Interest Group (AIIG), is to foster communication among the scientists of NIH, FDA and other agencies with diverse backgrounds who have a common interest in the development of artificial intelligence for the improve medical treatments. Topic include but not limit to artificial intelligence (AI), neural networks (CNN), algorithms, simulation, fuzzy logic, molecular and biological pattern recognition, biomarkers, biosensors, robotic platform technologies (RPT), and remote diagnosis and therapy (RDT). For information about the NIH Artificial Intelligence Interest Group (AIIG), contact Dr. June Lee, MD, Ph.D. at LeeJun@mail.nih.gov.
- **[ARTIFICIAL-INTELLIGENCE@LIST.NIH.GOV](https://list.nih.gov/cgi-bin/wa.exe?A0=ARTIFICIAL-INTELLIGENCE)**: The official mailing list for the Artificial Intelligence - Scientific Interest Group. We promote AI-related events happening on campus and run AI Club - a volunteer-led journal club/workshop/seminar series focused on all AI-related applications and topics in biomedical science.
- **[ATLASSIAN-USERS-GROUP@LIST.NIH.GOV](https://list.nih.gov/cgi-bin/wa.exe?A0=ATLASSIAN-USERS-GROUP)**: A list for sharing information about Atlassian products, licensing, and related software, as well as coordinating Atlassian user group meetings.
- **[ATSIG-L@LIST.NIH.GOV](https://list.nih.gov/cgi-bin/wa.exe?A0=ATSIG-L)**: The Advanced Technologies Special Interest Group (ATSIG) is being developed under the auspices of the NIH electronic Research Administration (eRA) initiative and was initially intended to explore technologies that would aid in improving business practices at the NIH. The prime example of that was the use of imaging technology to convert paper applications to electronic format. Since that effort has been successfully accomplished the eRA Advanced Technologies effort has been broadened to include many more areas of emphasis that will certainly change the way that work is done in the future. Examples include all aspects of computer technology, the workplace of the future, biometrics, nanotechnology and disability-related technology, to name but a few.
- **[BCIG-L@LIST.NIH.GOV](https://list.nih.gov/cgi-bin/wa.exe?A0=BCIG-L)**: The Biomedical Computing Interest Group (BCIG) is an interest group at The National Institutes of Health. The meetings are currently held in the Clinical Center in the Department of Clinical Research Informatics (10/1C290). Meeting days are every other Thursday and the time is 3:00 pm - 5:00 pm. A schedule of speakers is available.
- **[BD2KUPDATES@LIST.NIH.GOV](https://list.nih.gov/cgi-bin/wa.exe?A0=BD2KUPDATES)**: The purpose of this list is to send out notices of upcoming workshops and other pertinent information as relating to elements of Big Data to Knowledge BD2K.